// heure bleue -- languages, place and units, shared by the three pages.
//
// Where a choice comes from, first match wins:
//   language  ?lang=xx  ->  this browser (localStorage)  ->  config.json "language"
//             ->  config.json "locale" prefix  ->  the browser's own language  ->  en
//   place     this browser (localStorage)  ->  config.json "city"
//   units     this browser (localStorage)  ->  config.json "units"  ->  celsius
// The wall's own panel (the ⚙ button) writes the browser choices. "Reset" clears them.
//
// Adding a language: one more entry in LANGS below. Every key must be present;
// a missing key falls back to English at runtime, so a partial entry still works.
(() => {
  const LANGS = {
    en: { name: "English",
      mood: "matched to the album cover",
      match: "Matching", match_cover: "cover colours", match_music: "music feel", match_moment: "the moment", match_note: "what a choice listens to; turn any off, one stays on", why_lead: "chosen for {list}", and: "and", why_cover: "the {c} of the cover", why_music: "the {t} in the music", why_hour: "the {a} you just kept", why_today: "{a}'s day", why_taste: "the {a} you kept", col_black: "black", col_white: "white", col_grey: "grey", col_brown: "brown", col_beige: "beige", col_pink: "pink", col_red: "red", col_orange: "orange", col_yellow: "yellow", col_green: "green", col_teal: "teal", col_blue: "blue", col_violet: "violet", mo_night: "the night", mo_dawn: "first light", mo_dusk: "the blue hour", mo_evening: "the evening", mo_clear: "the clear sky", mo_overcast: "the grey sky", mo_fog: "the fog", mo_rain: "the rain", mo_snow: "the snow", mo_storm: "the storm", mo_spring: "spring", mo_summer: "summer", mo_autumn: "autumn", mo_winter: "winter", memory1: "a year ago today you kept {p}", memory1_song: "a year ago today you kept {p} while {s} played", memory: "{n} years ago today you kept {p}", memory_song: "{n} years ago today you kept {p} while {s} played", year_ready: "your {y} on the wall is ready · press Y", tip_year: "Your year as a card: the paintings you kept, month by month, to the Desktop", yr_title: "your year on the wall", yr_hours: "hours on the wall", yr_most_kept: "most kept", yr_museum: "your museum", yr_song: "the music behind the hearts", yr_painter: "the painter you lived with", yr_quiet: "quiet months", yr_none_quiet: "a painting kept every month", yr_card: "make my {y} card", yr_in_months: "paintings kept in {n} of 12 months",
      tip_theme: "Wall colour: nine tints, or the painting's own", tip_swap: "Another painting for the same song", tip_keep: "Keep this painting. The wall learns from what you keep", tip_kept: "Your kept paintings, with the song that was playing for each", tip_next: "Next song; the wall follows at once", tip_prefs: "Settings: language, place, units, pace, how the wall chooses, updates",
      st_loading: "loading the painting", st_museum: "the museum did not answer, trying another", st_choosing: "choosing another painting", st_reading: "reading the album cover", st_next: "next song", st_player: "the player did not answer",
      playing: "playing", paused: "paused", paused_rot: "paused · the wall rotates",
      sunset_in: "sunset in {n} min", blue_hour: "blue hour", set_at: "sun set at {t}", first_light_in: "first light in {n} min", blue_morning: "morning blue hour", rise_at: "risen at {t}",
      clear: "Clear sky", mostly_clear: "Mostly clear", partly: "Partly cloudy", overcast: "Overcast", fog: "Fog", rime: "Freezing fog", drizzle_l: "Light drizzle", drizzle: "Drizzle", drizzle_d: "Dense drizzle", fdrizzle: "Freezing drizzle", rain_l: "Light rain", rain: "Rain", rain_h: "Heavy rain", frain: "Freezing rain", snow_l: "Light snow", snow: "Snow", snow_h: "Heavy snow", showers: "Showers", showers_h: "Heavy showers", snow_showers: "Snow showers", storm: "Thunderstorm",
      language: "Language", place: "Place", search_city: "search a city", my_position: "use my position", locating: "locating…", not_found: "no place found", no_position: "position not available", units: "Units", reset: "reset to config.json", update: "new version {v} available", update_install: "new version {v} · install", upd_downloading: "downloading {p} %", upd_installing: "installing…", upd_restarting: "restarting…", upd_failed: "update failed · open the page", upd_ready: "new version {v} ready · restart", dismiss: "not now", updates: "Updates", upd_click: "ask me", upd_auto: "install at quit", ver_current: "version {v} · up to date", ver_newer: "version {v} · {n} available", demo_kicker: "web demo · no music here", demo_title: "The real wall listens to your music.", demo_sub: "The free app matches each painting to the album playing. No account, updates itself.", demo_how: "how to install", choice: "Choice", taste_on: "my taste", taste_off: "surprise me", taste_note: "my taste: kept paintings pull toward their artists, museums and centuries", made_by: "made by", source: "source", pace: "Pace", pace_note: "how long a painting stays when nothing is playing", tip_card: "Save a card of this wall to the Desktop: painting, label, song, the day's paintings", card_making: "drawing the card…", card_saved: "card saved to the Desktop", card_failed: "could not make the card", today_born: "{a}, born on this day in {y}", today_died: "{a}, died on this day in {y}", tip_export: "save the list as a file", tip_stats: "Stats: time on the wall by museum, century and painter", tip_full: "Fullscreen", tip_help: "What the buttons and keys do", help_title: "heure bleue", help_sub: "A gallery wall that follows your music. Everything is one key or one small button, bottom right.", help_close: "press any key to close · ? brings this back",
      kept: "Kept", wall: "wall", stats: "stats", museum: "museum", order: "order", newest: "newest", oldest: "oldest", artist: "artist", all: "all", empty_kept: "Nothing kept yet. Press L on the wall.", open: "open", remove: "remove", song_tip: "playing when you kept this",
      since: "since {d}", empty_stats: "Nothing yet.", empty_stats_sub: "The wall writes one line each time the painting changes.", nothing_yet: "nothing yet",
      shown: "paintings shown", works: "different works", on_wall: "on the wall", skipped: "skipped", with_music: "with music",
      museums: "Museums", time_on_wall: "time on the wall", centuries: "Centuries", century: "{n}th century", painters: "Painters", most_on_wall: "most on the wall", most_shown: "Most shown", sec_skipped: "Skipped", skipped_sub: "the ones you moved past", music: "Music", music_sub: "artists behind the wall", songs: "Songs", pairings: "Pairings", pairings_sub: "music artist → painter matched most", of: "{a} of {b}", by_museum: "by museum", songs_hearts: "Songs behind the hearts", hours: "Hours", hours_sub: "when the wall is on", h: "h", min: "min",
    },
    fr: { name: "Français",
      mood: "accordé à la pochette de l’album",
      match: "Accord", match_cover: "couleurs de la pochette", match_music: "esprit de la musique", match_moment: "le moment", match_note: "ce qu'un choix écoute ; on peut tout couper sauf un", why_lead: "choisi pour {list}", and: "et", why_cover: "le {c} de la pochette", why_music: "le {t} de la musique", why_hour: "{a}, que vous venez de garder", why_today: "le jour de {a}", why_taste: "{a}, que vous gardez", col_black: "noir", col_white: "blanc", col_grey: "gris", col_brown: "brun", col_beige: "beige", col_pink: "rose", col_red: "rouge", col_orange: "orangé", col_yellow: "jaune", col_green: "vert", col_teal: "bleu-vert", col_blue: "bleu", col_violet: "violet", mo_night: "la nuit", mo_dawn: "la première lueur", mo_dusk: "l'heure bleue", mo_evening: "le soir", mo_clear: "le ciel clair", mo_overcast: "le ciel gris", mo_fog: "le brouillard", mo_rain: "la pluie", mo_snow: "la neige", mo_storm: "l'orage", mo_spring: "le printemps", mo_summer: "l'été", mo_autumn: "l'automne", mo_winter: "l'hiver", memory1: "il y a un an, jour pour jour, vous gardiez {p}", memory1_song: "il y a un an, jour pour jour, vous gardiez {p} sur {s}", memory: "il y a {n} ans, jour pour jour, vous gardiez {p}", memory_song: "il y a {n} ans, jour pour jour, vous gardiez {p} sur {s}", year_ready: "votre {y} au mur est prête · touche Y", tip_year: "Votre année en carte : les tableaux gardés, mois par mois, sur le Bureau", yr_title: "votre année au mur", yr_hours: "heures au mur", yr_most_kept: "le plus gardé", yr_museum: "votre musée", yr_song: "la musique derrière les cœurs", yr_painter: "le peintre avec qui vous avez vécu", yr_quiet: "mois sans rien", yr_none_quiet: "un tableau gardé chaque mois", yr_card: "faire ma carte {y}", yr_in_months: "des tableaux gardés {n} mois sur 12",
      tip_theme: "Couleur du mur : neuf teintes, ou celle du tableau", tip_swap: "Un autre tableau pour la même chanson", tip_keep: "Garder ce tableau. Le mur apprend de ce que vous gardez", tip_kept: "Vos tableaux gardés, avec la chanson qui jouait", tip_next: "Chanson suivante ; le mur suit aussitôt", tip_prefs: "Réglages : langue, lieu, unités, rythme, façon de choisir, mises à jour",
      st_loading: "chargement du tableau", st_museum: "le musée ne répond pas, on en essaie un autre", st_choosing: "choix d’un autre tableau", st_reading: "lecture de la pochette", st_next: "chanson suivante", st_player: "le lecteur ne répond pas",
      playing: "en cours", paused: "en pause", paused_rot: "en pause · le mur tourne",
      sunset_in: "coucher du soleil dans {n} min", blue_hour: "heure bleue", set_at: "soleil couché à {t}", first_light_in: "première lueur dans {n} min", blue_morning: "heure bleue du matin", rise_at: "levé à {t}",
      clear: "Ciel clair", mostly_clear: "Presque clair", partly: "Quelques nuages", overcast: "Couvert", fog: "Brouillard", rime: "Brouillard givrant", drizzle_l: "Bruine légère", drizzle: "Bruine", drizzle_d: "Bruine dense", fdrizzle: "Bruine verglaçante", rain_l: "Pluie légère", rain: "Pluie", rain_h: "Pluie forte", frain: "Pluie verglaçante", snow_l: "Neige légère", snow: "Neige", snow_h: "Neige forte", showers: "Averses", showers_h: "Averses fortes", snow_showers: "Averses de neige", storm: "Orage",
      language: "Langue", place: "Lieu", search_city: "chercher une ville", my_position: "utiliser ma position", locating: "localisation…", not_found: "aucun lieu trouvé", no_position: "position indisponible", units: "Unités", reset: "revenir à config.json", update: "nouvelle version {v} disponible", update_install: "nouvelle version {v} · installer", upd_downloading: "téléchargement {p} %", upd_installing: "installation…", upd_restarting: "redémarrage…", upd_failed: "mise à jour impossible · ouvrir la page", upd_ready: "nouvelle version {v} prête · redémarrer", dismiss: "pas maintenant", updates: "Mises à jour", upd_click: "me demander", upd_auto: "installer en quittant", ver_current: "version {v} · à jour", ver_newer: "version {v} · {n} disponible", demo_kicker: "démo web · pas de musique ici", demo_title: "Le vrai mur écoute votre musique.", demo_sub: "L'application gratuite accorde chaque tableau à l'album en cours. Sans compte, se met à jour seule.", demo_how: "comment installer", choice: "Choix", taste_on: "mes goûts", taste_off: "surprenez-moi", taste_note: "mes goûts : les tableaux gardés attirent leurs artistes, musées et siècles", made_by: "créé par", source: "code source", pace: "Rythme", pace_note: "le temps qu'un tableau reste quand rien ne joue", tip_card: "Enregistrer une carte de ce mur sur le Bureau : tableau, cartel, chanson, tableaux du jour", card_making: "dessin de la carte…", card_saved: "carte enregistrée sur le Bureau", card_failed: "la carte n'a pas pu être faite", today_born: "{a}, né un jour comme aujourd'hui, en {y}", today_died: "{a}, mort un jour comme aujourd'hui, en {y}", tip_export: "enregistrer la liste dans un fichier", tip_stats: "Statistiques : temps au mur par musée, siècle et peintre", tip_full: "Plein écran", tip_help: "À quoi servent les boutons et les touches", help_title: "heure bleue", help_sub: "Un mur de tableaux qui suit votre musique. Tout tient en une touche ou un petit bouton, en bas à droite.", help_close: "une touche pour fermer · ? pour revenir ici",
      kept: "Gardés", wall: "mur", stats: "stats", museum: "musée", order: "ordre", newest: "récents", oldest: "anciens", artist: "artiste", all: "tous", empty_kept: "Rien de gardé pour l’instant. Appuyez sur L sur le mur.", open: "ouvrir", remove: "retirer", song_tip: "ce qui jouait quand vous l’avez gardé",
      since: "depuis le {d}", empty_stats: "Rien pour l’instant.", empty_stats_sub: "Le mur écrit une ligne à chaque changement de tableau.", nothing_yet: "rien pour l’instant",
      shown: "tableaux montrés", works: "œuvres différentes", on_wall: "sur le mur", skipped: "passés", with_music: "avec musique",
      museums: "Musées", time_on_wall: "temps sur le mur", centuries: "Siècles", century: "{n}e siècle", painters: "Peintres", most_on_wall: "les plus présents", most_shown: "Les plus montrés", sec_skipped: "Passés", skipped_sub: "ceux que vous avez sautés", music: "Musique", music_sub: "les artistes derrière le mur", songs: "Chansons", pairings: "Accords", pairings_sub: "artiste → peintre le plus souvent associé", of: "{a} sur {b}", by_museum: "par musée", songs_hearts: "Les chansons derrière les cœurs", hours: "Heures", hours_sub: "quand le mur est allumé", h: "h", min: "min",
    },
    nl: { name: "Nederlands",
      mood: "afgestemd op de albumhoes",
      match: "Afstemming", match_cover: "kleuren van de hoes", match_music: "sfeer van de muziek", match_moment: "het moment", match_note: "waar een keuze naar luistert; zet uit wat je wilt, één blijft aan", why_lead: "gekozen om {list}", and: "en", why_cover: "het {c} van de hoes", why_music: "de {t} in de muziek", why_hour: "{a}, die je net bewaarde", why_today: "de dag van {a}", why_taste: "{a}, die je bewaart", col_black: "zwart", col_white: "wit", col_grey: "grijs", col_brown: "bruin", col_beige: "beige", col_pink: "roze", col_red: "rood", col_orange: "oranje", col_yellow: "geel", col_green: "groen", col_teal: "blauwgroen", col_blue: "blauw", col_violet: "violet", mo_night: "de nacht", mo_dawn: "het eerste licht", mo_dusk: "het blauwe uur", mo_evening: "de avond", mo_clear: "de heldere hemel", mo_overcast: "de grijze lucht", mo_fog: "de mist", mo_rain: "de regen", mo_snow: "de sneeuw", mo_storm: "het onweer", mo_spring: "de lente", mo_summer: "de zomer", mo_autumn: "de herfst", mo_winter: "de winter", memory1: "een jaar geleden vandaag bewaarde je {p}", memory1_song: "een jaar geleden vandaag bewaarde je {p} bij {s}", memory: "{n} jaar geleden vandaag bewaarde je {p}", memory_song: "{n} jaar geleden vandaag bewaarde je {p} bij {s}", year_ready: "je {y} aan de wand is klaar · toets Y", tip_year: "Je jaar als kaart: de bewaarde schilderijen, maand voor maand, op het Bureaublad", yr_title: "je jaar aan de wand", yr_hours: "uren aan de wand", yr_most_kept: "meest bewaard", yr_museum: "je museum", yr_song: "de muziek achter de hartjes", yr_painter: "de schilder met wie je leefde", yr_quiet: "stille maanden", yr_none_quiet: "elke maand een schilderij bewaard", yr_card: "maak mijn kaart {y}", yr_in_months: "schilderijen bewaard in {n} van 12 maanden",
      tip_theme: "Wandkleur: negen tinten, of die van het schilderij", tip_swap: "Een ander schilderij bij hetzelfde nummer", tip_keep: "Dit schilderij bewaren. De wand leert van wat je bewaart", tip_kept: "Je bewaarde schilderijen, met het nummer dat speelde", tip_next: "Volgend nummer; de wand volgt meteen", tip_prefs: "Instellingen: taal, plaats, eenheden, tempo, hoe de wand kiest, updates",
      st_loading: "schilderij wordt geladen", st_museum: "het museum antwoordt niet, we proberen een ander", st_choosing: "een ander schilderij kiezen", st_reading: "de albumhoes lezen", st_next: "volgend nummer", st_player: "de speler antwoordt niet",
      playing: "speelt", paused: "gepauzeerd", paused_rot: "gepauzeerd · de muur wisselt",
      sunset_in: "zonsondergang over {n} min", blue_hour: "blauwe uur", set_at: "zon onder om {t}", first_light_in: "eerste licht over {n} min", blue_morning: "blauwe uur van de ochtend", rise_at: "opgekomen om {t}",
      clear: "Heldere hemel", mostly_clear: "Vrijwel helder", partly: "Half bewolkt", overcast: "Bewolkt", fog: "Mist", rime: "Aanvriezende mist", drizzle_l: "Lichte motregen", drizzle: "Motregen", drizzle_d: "Dichte motregen", fdrizzle: "IJzel (motregen)", rain_l: "Lichte regen", rain: "Regen", rain_h: "Zware regen", frain: "IJzel", snow_l: "Lichte sneeuw", snow: "Sneeuw", snow_h: "Zware sneeuw", showers: "Buien", showers_h: "Zware buien", snow_showers: "Sneeuwbuien", storm: "Onweer",
      language: "Taal", place: "Plaats", search_city: "zoek een stad", my_position: "mijn positie gebruiken", locating: "locatie bepalen…", not_found: "geen plaats gevonden", no_position: "positie niet beschikbaar", units: "Eenheden", reset: "terug naar config.json", update: "nieuwe versie {v} beschikbaar", update_install: "nieuwe versie {v} · installeren", upd_downloading: "downloaden {p} %", upd_installing: "installeren…", upd_restarting: "herstarten…", upd_failed: "update mislukt · pagina openen", upd_ready: "nieuwe versie {v} klaar · herstarten", dismiss: "niet nu", updates: "Updates", upd_click: "vraag mij", upd_auto: "installeren bij afsluiten", ver_current: "versie {v} · actueel", ver_newer: "versie {v} · {n} beschikbaar", demo_kicker: "webdemo · hier geen muziek", demo_title: "De echte wand luistert naar je muziek.", demo_sub: "De gratis app kiest elk schilderij bij het album dat speelt. Geen account, werkt zichzelf bij.", demo_how: "hoe te installeren", choice: "Keuze", taste_on: "mijn smaak", taste_off: "verras me", taste_note: "mijn smaak: bewaarde schilderijen trekken naar hun kunstenaars, musea en eeuwen", made_by: "gemaakt door", source: "broncode", pace: "Tempo", pace_note: "hoe lang een schilderij blijft als er niets speelt", tip_card: "Een kaart van deze wand op het Bureaublad bewaren: schilderij, label, nummer, de schilderijen van vandaag", card_making: "kaart wordt getekend…", card_saved: "kaart bewaard op het Bureaublad", card_failed: "kaart kon niet gemaakt worden", today_born: "{a}, geboren op deze dag in {y}", today_died: "{a}, overleden op deze dag in {y}", tip_export: "de lijst als bestand bewaren", tip_stats: "Statistieken: tijd aan de wand per museum, eeuw en schilder", tip_full: "Volledig scherm", tip_help: "Wat de knoppen en toetsen doen", help_title: "heure bleue", help_sub: "Een schilderijenwand die je muziek volgt. Alles is één toets of één klein knopje, rechtsonder.", help_close: "druk een toets om te sluiten · ? brengt dit terug",
      kept: "Bewaard", wall: "muur", stats: "statistieken", museum: "museum", order: "volgorde", newest: "nieuwste", oldest: "oudste", artist: "kunstenaar", all: "alle", empty_kept: "Nog niets bewaard. Druk op L op de muur.", open: "openen", remove: "verwijderen", song_tip: "speelde toen je dit bewaarde",
      since: "sinds {d}", empty_stats: "Nog niets.", empty_stats_sub: "De muur schrijft een regel bij elke wissel van schilderij.", nothing_yet: "nog niets",
      shown: "schilderijen getoond", works: "verschillende werken", on_wall: "aan de muur", skipped: "overgeslagen", with_music: "met muziek",
      museums: "Musea", time_on_wall: "tijd aan de muur", centuries: "Eeuwen", century: "{n}e eeuw", painters: "Schilders", most_on_wall: "meest aan de muur", most_shown: "Meest getoond", sec_skipped: "Overgeslagen", skipped_sub: "die je voorbij liet gaan", music: "Muziek", music_sub: "de artiesten achter de muur", songs: "Nummers", pairings: "Paren", pairings_sub: "muzikant → vaakst gekoppelde schilder", of: "{a} van {b}", by_museum: "per museum", songs_hearts: "Nummers achter de hartjes", hours: "Uren", hours_sub: "wanneer de muur aan is", h: "u", min: "min",
    },
    de: { name: "Deutsch",
      mood: "auf das Albumcover abgestimmt",
      match: "Abstimmung", match_cover: "Farben des Covers", match_music: "Stimmung der Musik", match_moment: "der Moment", match_note: "worauf eine Wahl hört; alles abschaltbar, eines bleibt an", why_lead: "gewählt für {list}", and: "und", why_cover: "das {c} des Covers", why_music: "den {t} in der Musik", why_hour: "{a}, gerade behalten", why_today: "den Tag von {a}", why_taste: "{a}, den du behältst", col_black: "Schwarz", col_white: "Weiß", col_grey: "Grau", col_brown: "Braun", col_beige: "Beige", col_pink: "Rosa", col_red: "Rot", col_orange: "Orange", col_yellow: "Gelb", col_green: "Grün", col_teal: "Blaugrün", col_blue: "Blau", col_violet: "Violett", mo_night: "die Nacht", mo_dawn: "das erste Licht", mo_dusk: "die blaue Stunde", mo_evening: "den Abend", mo_clear: "den klaren Himmel", mo_overcast: "den grauen Himmel", mo_fog: "den Nebel", mo_rain: "den Regen", mo_snow: "den Schnee", mo_storm: "das Gewitter", mo_spring: "den Frühling", mo_summer: "den Sommer", mo_autumn: "den Herbst", mo_winter: "den Winter", memory1: "heute vor einem Jahr hast du {p} behalten", memory1_song: "heute vor einem Jahr hast du {p} behalten, zu {s}", memory: "heute vor {n} Jahren hast du {p} behalten", memory_song: "heute vor {n} Jahren hast du {p} behalten, zu {s}", year_ready: "dein {y} an der Wand ist bereit · Taste Y", tip_year: "Dein Jahr als Karte: die behaltenen Bilder, Monat für Monat, auf den Schreibtisch", yr_title: "dein Jahr an der Wand", yr_hours: "Stunden an der Wand", yr_most_kept: "am meisten behalten", yr_museum: "dein Museum", yr_song: "die Musik hinter den Herzen", yr_painter: "der Maler, mit dem du gelebt hast", yr_quiet: "stille Monate", yr_none_quiet: "jeden Monat ein Bild behalten", yr_card: "meine Karte {y} machen", yr_in_months: "Bilder in {n} von 12 Monaten behalten",
      tip_theme: "Wandfarbe: neun Töne, oder die des Bildes", tip_swap: "Ein anderes Bild zum selben Lied", tip_keep: "Dieses Bild behalten. Die Wand lernt aus dem, was du behältst", tip_kept: "Deine behaltenen Bilder, mit dem Lied, das dabei lief", tip_next: "Nächstes Lied; die Wand folgt sofort", tip_prefs: "Einstellungen: Sprache, Ort, Einheiten, Tempo, Auswahl, Updates",
      st_loading: "Gemälde wird geladen", st_museum: "das Museum antwortet nicht, ein anderes wird versucht", st_choosing: "ein anderes Gemälde wird gewählt", st_reading: "das Albumcover wird gelesen", st_next: "nächstes Lied", st_player: "der Player antwortet nicht",
      playing: "läuft", paused: "pausiert", paused_rot: "pausiert · die Wand wechselt",
      sunset_in: "Sonnenuntergang in {n} Min", blue_hour: "blaue Stunde", set_at: "Sonne untergegangen um {t}", first_light_in: "erstes Licht in {n} Min", blue_morning: "blaue Stunde am Morgen", rise_at: "aufgegangen um {t}",
      clear: "Klarer Himmel", mostly_clear: "Überwiegend klar", partly: "Teils bewölkt", overcast: "Bedeckt", fog: "Nebel", rime: "Gefrierender Nebel", drizzle_l: "Leichter Sprühregen", drizzle: "Sprühregen", drizzle_d: "Dichter Sprühregen", fdrizzle: "Gefrierender Sprühregen", rain_l: "Leichter Regen", rain: "Regen", rain_h: "Starker Regen", frain: "Gefrierender Regen", snow_l: "Leichter Schnee", snow: "Schnee", snow_h: "Starker Schnee", showers: "Schauer", showers_h: "Starke Schauer", snow_showers: "Schneeschauer", storm: "Gewitter",
      language: "Sprache", place: "Ort", search_city: "Stadt suchen", my_position: "meinen Standort verwenden", locating: "Standort wird bestimmt…", not_found: "kein Ort gefunden", no_position: "Standort nicht verfügbar", units: "Einheiten", reset: "zurück zu config.json", update: "neue Version {v} verfügbar", update_install: "neue Version {v} · installieren", upd_downloading: "wird geladen {p} %", upd_installing: "wird installiert…", upd_restarting: "Neustart…", upd_failed: "Update fehlgeschlagen · Seite öffnen", upd_ready: "neue Version {v} bereit · Neustart", dismiss: "nicht jetzt", updates: "Updates", upd_click: "nachfragen", upd_auto: "beim Beenden installieren", ver_current: "Version {v} · aktuell", ver_newer: "Version {v} · {n} verfügbar", demo_kicker: "Web-Demo · hier keine Musik", demo_title: "Die echte Wand hört deine Musik.", demo_sub: "Die kostenlose App passt jedes Bild zum laufenden Album. Kein Konto, aktualisiert sich selbst.", demo_how: "Installation", choice: "Auswahl", taste_on: "mein Geschmack", taste_off: "überrasch mich", taste_note: "mein Geschmack: behaltene Bilder ziehen zu ihren Künstlern, Museen und Jahrhunderten", made_by: "gemacht von", source: "Quellcode", pace: "Tempo", pace_note: "wie lange ein Bild bleibt, wenn nichts spielt", tip_card: "Eine Karte dieser Wand auf dem Schreibtisch speichern: Bild, Schild, Lied, die Bilder des Tages", card_making: "Karte wird gezeichnet…", card_saved: "Karte auf dem Schreibtisch gespeichert", card_failed: "Karte konnte nicht erstellt werden", today_born: "{a}, an diesem Tag geboren, {y}", today_died: "{a}, an diesem Tag gestorben, {y}", tip_export: "die Liste als Datei speichern", tip_stats: "Statistik: Zeit an der Wand nach Museum, Jahrhundert und Maler", tip_full: "Vollbild", tip_help: "Was die Knöpfe und Tasten tun", help_title: "heure bleue", help_sub: "Eine Bilderwand, die deiner Musik folgt. Alles ist eine Taste oder ein kleiner Knopf unten rechts.", help_close: "eine Taste schließt · ? bringt dies zurück",
      kept: "Behalten", wall: "Wand", stats: "Statistik", museum: "Museum", order: "Reihenfolge", newest: "neueste", oldest: "älteste", artist: "Künstler", all: "alle", empty_kept: "Noch nichts behalten. Drücke L auf der Wand.", open: "öffnen", remove: "entfernen", song_tip: "lief, als du dieses behalten hast",
      since: "seit {d}", empty_stats: "Noch nichts.", empty_stats_sub: "Die Wand schreibt bei jedem Gemäldewechsel eine Zeile.", nothing_yet: "noch nichts",
      shown: "Gemälde gezeigt", works: "verschiedene Werke", on_wall: "an der Wand", skipped: "übersprungen", with_music: "mit Musik",
      museums: "Museen", time_on_wall: "Zeit an der Wand", centuries: "Jahrhunderte", century: "{n}. Jahrhundert", painters: "Maler", most_on_wall: "am längsten an der Wand", most_shown: "Am häufigsten gezeigt", sec_skipped: "Übersprungen", skipped_sub: "die du weitergeklickt hast", music: "Musik", music_sub: "die Künstler hinter der Wand", songs: "Lieder", pairings: "Paare", pairings_sub: "Musiker → am häufigsten zugeordneter Maler", of: "{a} von {b}", by_museum: "nach Museum", songs_hearts: "Lieder hinter den Herzen", hours: "Stunden", hours_sub: "wann die Wand an ist", h: "Std", min: "Min",
    },
    es: { name: "Español",
      mood: "a juego con la portada del álbum",
      match: "Afinación", match_cover: "colores de la portada", match_music: "aire de la música", match_moment: "el momento", match_note: "lo que escucha una elección; apaga lo que quieras, uno queda", why_lead: "elegido por {list}", and: "y", why_cover: "el {c} de la portada", why_music: "el {t} de la música", why_hour: "{a}, que acabas de guardar", why_today: "el día de {a}", why_taste: "{a}, que guardas", col_black: "negro", col_white: "blanco", col_grey: "gris", col_brown: "marrón", col_beige: "beige", col_pink: "rosa", col_red: "rojo", col_orange: "naranja", col_yellow: "amarillo", col_green: "verde", col_teal: "verde azulado", col_blue: "azul", col_violet: "violeta", mo_night: "la noche", mo_dawn: "la primera luz", mo_dusk: "la hora azul", mo_evening: "la tarde", mo_clear: "el cielo despejado", mo_overcast: "el cielo gris", mo_fog: "la niebla", mo_rain: "la lluvia", mo_snow: "la nieve", mo_storm: "la tormenta", mo_spring: "la primavera", mo_summer: "el verano", mo_autumn: "el otoño", mo_winter: "el invierno", memory1: "hace un año, tal día como hoy, guardaste {p}", memory1_song: "hace un año, tal día como hoy, guardaste {p} con {s}", memory: "hace {n} años, tal día como hoy, guardaste {p}", memory_song: "hace {n} años, tal día como hoy, guardaste {p} con {s}", year_ready: "tu {y} en el muro está listo · tecla Y", tip_year: "Tu año en una tarjeta: los cuadros guardados, mes a mes, en el Escritorio", yr_title: "tu año en el muro", yr_hours: "horas en el muro", yr_most_kept: "más guardado", yr_museum: "tu museo", yr_song: "la música detrás de los corazones", yr_painter: "el pintor con quien viviste", yr_quiet: "meses en silencio", yr_none_quiet: "un cuadro guardado cada mes", yr_card: "hacer mi tarjeta {y}", yr_in_months: "cuadros guardados en {n} de 12 meses",
      tip_theme: "Color del muro: nueve tonos, o el del cuadro", tip_swap: "Otro cuadro para la misma canción", tip_keep: "Guardar este cuadro. El muro aprende de lo que guardas", tip_kept: "Tus cuadros guardados, con la canción que sonaba", tip_next: "Siguiente canción; el muro la sigue al momento", tip_prefs: "Ajustes: idioma, lugar, unidades, ritmo, cómo elige el muro, actualizaciones",
      st_loading: "cargando el cuadro", st_museum: "el museo no responde, probamos otro", st_choosing: "eligiendo otro cuadro", st_reading: "leyendo la portada del álbum", st_next: "siguiente canción", st_player: "el reproductor no responde",
      playing: "sonando", paused: "en pausa", paused_rot: "en pausa · la pared rota",
      sunset_in: "puesta de sol en {n} min", blue_hour: "hora azul", set_at: "sol puesto a las {t}", first_light_in: "primera luz en {n} min", blue_morning: "hora azul de la mañana", rise_at: "salido a las {t}",
      clear: "Cielo despejado", mostly_clear: "Casi despejado", partly: "Parcialmente nublado", overcast: "Cubierto", fog: "Niebla", rime: "Niebla helada", drizzle_l: "Llovizna ligera", drizzle: "Llovizna", drizzle_d: "Llovizna densa", fdrizzle: "Llovizna helada", rain_l: "Lluvia ligera", rain: "Lluvia", rain_h: "Lluvia fuerte", frain: "Lluvia helada", snow_l: "Nieve ligera", snow: "Nieve", snow_h: "Nieve fuerte", showers: "Chubascos", showers_h: "Chubascos fuertes", snow_showers: "Chubascos de nieve", storm: "Tormenta",
      language: "Idioma", place: "Lugar", search_city: "buscar una ciudad", my_position: "usar mi posición", locating: "localizando…", not_found: "ningún lugar encontrado", no_position: "posición no disponible", units: "Unidades", reset: "volver a config.json", update: "nueva versión {v} disponible", update_install: "nueva versión {v} · instalar", upd_downloading: "descargando {p} %", upd_installing: "instalando…", upd_restarting: "reiniciando…", upd_failed: "actualización fallida · abrir la página", upd_ready: "nueva versión {v} lista · reiniciar", dismiss: "ahora no", updates: "Actualizaciones", upd_click: "preguntarme", upd_auto: "instalar al salir", ver_current: "versión {v} · al día", ver_newer: "versión {v} · {n} disponible", demo_kicker: "demo web · aquí sin música", demo_title: "El muro real escucha tu música.", demo_sub: "La aplicación gratuita acompaña cada cuadro al álbum que suena. Sin cuenta, se actualiza sola.", demo_how: "cómo instalar", choice: "Elección", taste_on: "mi gusto", taste_off: "sorpréndeme", taste_note: "mi gusto: los cuadros guardados tiran hacia sus artistas, museos y siglos", made_by: "hecho por", source: "código fuente", pace: "Ritmo", pace_note: "cuánto se queda un cuadro cuando nada suena", tip_card: "Guardar una tarjeta de este muro en el Escritorio: cuadro, cartela, canción, los cuadros del día", card_making: "dibujando la tarjeta…", card_saved: "tarjeta guardada en el Escritorio", card_failed: "no se pudo crear la tarjeta", today_born: "{a}, nacido tal día como hoy de {y}", today_died: "{a}, fallecido tal día como hoy de {y}", tip_export: "guardar la lista como archivo", tip_stats: "Estadísticas: tiempo en el muro por museo, siglo y pintor", tip_full: "Pantalla completa", tip_help: "Qué hacen los botones y las teclas", help_title: "heure bleue", help_sub: "Un muro de cuadros que sigue tu música. Todo cabe en una tecla o un botón pequeño, abajo a la derecha.", help_close: "pulsa una tecla para cerrar · ? vuelve aquí",
      kept: "Guardados", wall: "pared", stats: "estadísticas", museum: "museo", order: "orden", newest: "recientes", oldest: "antiguos", artist: "artista", all: "todos", empty_kept: "Nada guardado todavía. Pulsa L en la pared.", open: "abrir", remove: "quitar", song_tip: "sonaba cuando lo guardaste",
      since: "desde el {d}", empty_stats: "Nada todavía.", empty_stats_sub: "La pared escribe una línea cada vez que cambia el cuadro.", nothing_yet: "nada todavía",
      shown: "cuadros mostrados", works: "obras distintas", on_wall: "en la pared", skipped: "saltados", with_music: "con música",
      museums: "Museos", time_on_wall: "tiempo en la pared", centuries: "Siglos", century: "siglo {n}", painters: "Pintores", most_on_wall: "más tiempo en la pared", most_shown: "Más mostrados", sec_skipped: "Saltados", skipped_sub: "los que pasaste de largo", music: "Música", music_sub: "los artistas detrás de la pared", songs: "Canciones", pairings: "Parejas", pairings_sub: "músico → pintor emparejado más veces", of: "{a} de {b}", by_museum: "por museo", songs_hearts: "Canciones detrás de los corazones", hours: "Horas", hours_sub: "cuándo está encendida la pared", h: "h", min: "min",
    },
    it: { name: "Italiano",
      mood: "in accordo con la copertina dell’album",
      match: "Accordo", match_cover: "colori della copertina", match_music: "spirito della musica", match_moment: "il momento", match_note: "ciò che una scelta ascolta; spegni quel che vuoi, uno resta", why_lead: "scelto per {list}", and: "e", why_cover: "il {c} della copertina", why_music: "il {t} nella musica", why_hour: "{a}, che hai appena conservato", why_today: "il giorno di {a}", why_taste: "{a}, che conservi", col_black: "nero", col_white: "bianco", col_grey: "grigio", col_brown: "marrone", col_beige: "beige", col_pink: "rosa", col_red: "rosso", col_orange: "arancio", col_yellow: "giallo", col_green: "verde", col_teal: "verde acqua", col_blue: "blu", col_violet: "viola", mo_night: "la notte", mo_dawn: "la prima luce", mo_dusk: "l'ora blu", mo_evening: "la sera", mo_clear: "il cielo sereno", mo_overcast: "il cielo grigio", mo_fog: "la nebbia", mo_rain: "la pioggia", mo_snow: "la neve", mo_storm: "il temporale", mo_spring: "la primavera", mo_summer: "l'estate", mo_autumn: "l'autunno", mo_winter: "l'inverno", memory1: "un anno fa, oggi, conservavi {p}", memory1_song: "un anno fa, oggi, conservavi {p} su {s}", memory: "{n} anni fa, oggi, conservavi {p}", memory_song: "{n} anni fa, oggi, conservavi {p} su {s}", year_ready: "il tuo {y} al muro è pronto · tasto Y", tip_year: "Il tuo anno in una cartolina: i quadri conservati, mese per mese, sulla Scrivania", yr_title: "il tuo anno al muro", yr_hours: "ore al muro", yr_most_kept: "il più conservato", yr_museum: "il tuo museo", yr_song: "la musica dietro i cuori", yr_painter: "il pittore con cui hai vissuto", yr_quiet: "mesi silenziosi", yr_none_quiet: "un quadro conservato ogni mese", yr_card: "fai la mia cartolina {y}", yr_in_months: "quadri conservati in {n} mesi su 12",
      tip_theme: "Colore del muro: nove tinte, o quella del quadro", tip_swap: "Un altro quadro per la stessa canzone", tip_keep: "Conserva questo quadro. Il muro impara da ciò che conservi", tip_kept: "I quadri che hai conservato, con la canzone che suonava", tip_next: "Canzone successiva; il muro la segue subito", tip_prefs: "Impostazioni: lingua, luogo, unità, ritmo, come sceglie il muro, aggiornamenti",
      st_loading: "caricamento del quadro", st_museum: "il museo non risponde, ne proviamo un altro", st_choosing: "scelta di un altro quadro", st_reading: "lettura della copertina", st_next: "prossimo brano", st_player: "il lettore non risponde",
      playing: "in riproduzione", paused: "in pausa", paused_rot: "in pausa · la parete ruota",
      sunset_in: "tramonto tra {n} min", blue_hour: "ora blu", set_at: "sole tramontato alle {t}", first_light_in: "prima luce tra {n} min", blue_morning: "ora blu del mattino", rise_at: "sorto alle {t}",
      clear: "Cielo sereno", mostly_clear: "Quasi sereno", partly: "Parzialmente nuvoloso", overcast: "Coperto", fog: "Nebbia", rime: "Nebbia gelata", drizzle_l: "Pioggerella leggera", drizzle: "Pioggerella", drizzle_d: "Pioggerella fitta", fdrizzle: "Pioggerella gelata", rain_l: "Pioggia leggera", rain: "Pioggia", rain_h: "Pioggia forte", frain: "Pioggia gelata", snow_l: "Neve leggera", snow: "Neve", snow_h: "Neve forte", showers: "Rovesci", showers_h: "Rovesci forti", snow_showers: "Rovesci di neve", storm: "Temporale",
      language: "Lingua", place: "Luogo", search_city: "cerca una città", my_position: "usa la mia posizione", locating: "localizzazione…", not_found: "nessun luogo trovato", no_position: "posizione non disponibile", units: "Unità", reset: "torna a config.json", update: "nuova versione {v} disponibile", update_install: "nuova versione {v} · installa", upd_downloading: "download {p} %", upd_installing: "installazione…", upd_restarting: "riavvio…", upd_failed: "aggiornamento fallito · apri la pagina", upd_ready: "nuova versione {v} pronta · riavvia", dismiss: "non ora", updates: "Aggiornamenti", upd_click: "chiedimi", upd_auto: "installa alla chiusura", ver_current: "versione {v} · aggiornata", ver_newer: "versione {v} · {n} disponibile", demo_kicker: "demo web · qui niente musica", demo_title: "Il muro vero ascolta la tua musica.", demo_sub: "L'app gratuita abbina ogni quadro all'album in riproduzione. Nessun account, si aggiorna da sola.", demo_how: "come installare", choice: "Scelta", taste_on: "i miei gusti", taste_off: "sorprendimi", taste_note: "i miei gusti: i quadri conservati attirano i loro artisti, musei e secoli", made_by: "creato da", source: "codice sorgente", pace: "Ritmo", pace_note: "quanto resta un quadro quando non suona nulla", tip_card: "Salva una cartolina di questo muro sulla Scrivania: quadro, didascalia, canzone, i quadri del giorno", card_making: "disegno la cartolina…", card_saved: "cartolina salvata sulla Scrivania", card_failed: "impossibile creare la cartolina", today_born: "{a}, nato in questo giorno del {y}", today_died: "{a}, morto in questo giorno del {y}", tip_export: "salva l'elenco come file", tip_stats: "Statistiche: tempo al muro per museo, secolo e pittore", tip_full: "Schermo intero", tip_help: "Cosa fanno i pulsanti e i tasti", help_title: "heure bleue", help_sub: "Un muro di quadri che segue la tua musica. Tutto sta in un tasto o in un piccolo pulsante, in basso a destra.", help_close: "premi un tasto per chiudere · ? riporta qui",
      kept: "Tenuti", wall: "parete", stats: "statistiche", museum: "museo", order: "ordine", newest: "recenti", oldest: "vecchi", artist: "artista", all: "tutti", empty_kept: "Niente di tenuto per ora. Premi L sulla parete.", open: "apri", remove: "rimuovi", song_tip: "suonava quando l’hai tenuto",
      since: "dal {d}", empty_stats: "Niente per ora.", empty_stats_sub: "La parete scrive una riga a ogni cambio di quadro.", nothing_yet: "niente per ora",
      shown: "quadri mostrati", works: "opere diverse", on_wall: "sulla parete", skipped: "saltati", with_music: "con musica",
      museums: "Musei", time_on_wall: "tempo sulla parete", centuries: "Secoli", century: "{n}° secolo", painters: "Pittori", most_on_wall: "più a lungo sulla parete", most_shown: "Più mostrati", sec_skipped: "Saltati", skipped_sub: "quelli che hai saltato", music: "Musica", music_sub: "gli artisti dietro la parete", songs: "Brani", pairings: "Coppie", pairings_sub: "musicista → pittore abbinato più spesso", of: "{a} su {b}", by_museum: "per museo", songs_hearts: "Brani dietro i cuori", hours: "Ore", hours_sub: "quando la parete è accesa", h: "h", min: "min",
    },
    pt: { name: "Português",
      mood: "a combinar com a capa do álbum",
      match: "Afinação", match_cover: "cores da capa", match_music: "espírito da música", match_moment: "o momento", match_note: "o que uma escolha ouve; desligue o que quiser, um fica", why_lead: "escolhido por {list}", and: "e", why_cover: "o {c} da capa", why_music: "o {t} na música", why_hour: "{a}, que acabou de guardar", why_today: "o dia de {a}", why_taste: "{a}, que guarda", col_black: "preto", col_white: "branco", col_grey: "cinzento", col_brown: "castanho", col_beige: "bege", col_pink: "rosa", col_red: "vermelho", col_orange: "laranja", col_yellow: "amarelo", col_green: "verde", col_teal: "verde-azulado", col_blue: "azul", col_violet: "violeta", mo_night: "a noite", mo_dawn: "a primeira luz", mo_dusk: "a hora azul", mo_evening: "o fim do dia", mo_clear: "o céu limpo", mo_overcast: "o céu cinzento", mo_fog: "o nevoeiro", mo_rain: "a chuva", mo_snow: "a neve", mo_storm: "a trovoada", mo_spring: "a primavera", mo_summer: "o verão", mo_autumn: "o outono", mo_winter: "o inverno", memory1: "há um ano, neste dia, guardou {p}", memory1_song: "há um ano, neste dia, guardou {p} com {s}", memory: "há {n} anos, neste dia, guardou {p}", memory_song: "há {n} anos, neste dia, guardou {p} com {s}", year_ready: "o seu {y} na parede está pronto · tecla Y", tip_year: "O seu ano num cartão: os quadros guardados, mês a mês, no Ambiente de trabalho", yr_title: "o seu ano na parede", yr_hours: "horas na parede", yr_most_kept: "mais guardado", yr_museum: "o seu museu", yr_song: "a música por trás dos corações", yr_painter: "o pintor com quem viveu", yr_quiet: "meses em silêncio", yr_none_quiet: "um quadro guardado todos os meses", yr_card: "fazer o meu cartão {y}", yr_in_months: "quadros guardados em {n} de 12 meses",
      tip_theme: "Cor da parede: nove tons, ou a do quadro", tip_swap: "Outro quadro para a mesma música", tip_keep: "Guardar este quadro. A parede aprende com o que guarda", tip_kept: "Os seus quadros guardados, com a música que tocava", tip_next: "Próxima música; a parede segue logo", tip_prefs: "Definições: idioma, lugar, unidades, ritmo, como a parede escolhe, atualizações",
      st_loading: "a carregar o quadro", st_museum: "o museu não responde, a tentar outro", st_choosing: "a escolher outro quadro", st_reading: "a ler a capa do álbum", st_next: "próxima música", st_player: "o leitor não responde",
      playing: "a tocar", paused: "em pausa", paused_rot: "em pausa · a parede roda",
      sunset_in: "pôr do sol em {n} min", blue_hour: "hora azul", set_at: "sol posto às {t}", first_light_in: "primeira luz em {n} min", blue_morning: "hora azul da manhã", rise_at: "nascido às {t}",
      clear: "Céu limpo", mostly_clear: "Quase limpo", partly: "Parcialmente nublado", overcast: "Encoberto", fog: "Nevoeiro", rime: "Nevoeiro gelado", drizzle_l: "Chuvisco fraco", drizzle: "Chuvisco", drizzle_d: "Chuvisco denso", fdrizzle: "Chuvisco gelado", rain_l: "Chuva fraca", rain: "Chuva", rain_h: "Chuva forte", frain: "Chuva gelada", snow_l: "Neve fraca", snow: "Neve", snow_h: "Neve forte", showers: "Aguaceiros", showers_h: "Aguaceiros fortes", snow_showers: "Aguaceiros de neve", storm: "Trovoada",
      language: "Idioma", place: "Lugar", search_city: "procurar uma cidade", my_position: "usar a minha posição", locating: "a localizar…", not_found: "nenhum lugar encontrado", no_position: "posição indisponível", units: "Unidades", reset: "voltar a config.json", update: "nova versão {v} disponível", update_install: "nova versão {v} · instalar", upd_downloading: "a transferir {p} %", upd_installing: "a instalar…", upd_restarting: "a reiniciar…", upd_failed: "atualização falhou · abrir a página", upd_ready: "nova versão {v} pronta · reiniciar", dismiss: "agora não", updates: "Atualizações", upd_click: "perguntar-me", upd_auto: "instalar ao sair", ver_current: "versão {v} · atualizada", ver_newer: "versão {v} · {n} disponível", demo_kicker: "demo web · aqui sem música", demo_title: "A parede a sério ouve a sua música.", demo_sub: "A aplicação gratuita combina cada quadro com o álbum que toca. Sem conta, atualiza-se sozinha.", demo_how: "como instalar", choice: "Escolha", taste_on: "o meu gosto", taste_off: "surpreende-me", taste_note: "o meu gosto: os quadros guardados puxam para os seus artistas, museus e séculos", made_by: "feito por", source: "código-fonte", pace: "Ritmo", pace_note: "quanto tempo um quadro fica quando nada toca", tip_card: "Guardar um cartão desta parede no Ambiente de trabalho: quadro, legenda, música, os quadros do dia", card_making: "a desenhar o cartão…", card_saved: "cartão guardado no Ambiente de trabalho", card_failed: "não foi possível criar o cartão", today_born: "{a}, nascido neste dia em {y}", today_died: "{a}, falecido neste dia em {y}", tip_export: "guardar a lista como ficheiro", tip_stats: "Estatísticas: tempo na parede por museu, século e pintor", tip_full: "Ecrã inteiro", tip_help: "O que fazem os botões e as teclas", help_title: "heure bleue", help_sub: "Uma parede de quadros que segue a sua música. Tudo cabe numa tecla ou num botão pequeno, em baixo à direita.", help_close: "prima uma tecla para fechar · ? traz isto de volta",
      kept: "Guardados", wall: "parede", stats: "estatísticas", museum: "museu", order: "ordem", newest: "recentes", oldest: "antigos", artist: "artista", all: "todos", empty_kept: "Nada guardado ainda. Prima L na parede.", open: "abrir", remove: "remover", song_tip: "tocava quando guardou este",
      since: "desde {d}", empty_stats: "Nada ainda.", empty_stats_sub: "A parede escreve uma linha a cada mudança de quadro.", nothing_yet: "nada ainda",
      shown: "quadros mostrados", works: "obras diferentes", on_wall: "na parede", skipped: "saltados", with_music: "com música",
      museums: "Museus", time_on_wall: "tempo na parede", centuries: "Séculos", century: "século {n}", painters: "Pintores", most_on_wall: "mais tempo na parede", most_shown: "Mais mostrados", sec_skipped: "Saltados", skipped_sub: "os que passou à frente", music: "Música", music_sub: "os artistas por trás da parede", songs: "Músicas", pairings: "Pares", pairings_sub: "músico → pintor mais vezes emparelhado", of: "{a} de {b}", by_museum: "por museu", songs_hearts: "Músicas por trás dos corações", hours: "Horas", hours_sub: "quando a parede está ligada", h: "h", min: "min",
    },
    fi: { name: "Suomi",
      mood: "sovitettu albumin kanteen",
      match: "Sovitus", match_cover: "kannen värit", match_music: "musiikin tunnelma", match_moment: "hetki", match_note: "mitä valinta kuuntelee; sammuta mitä haluat, yksi jää päälle", why_lead: "valittu: {list}", and: "ja", why_cover: "kannen {c}", why_music: "musiikin {t}", why_hour: "{a}, jonka juuri säilytit", why_today: "{a}n päivä", why_taste: "{a}, jota säilytät", col_black: "musta", col_white: "valkoinen", col_grey: "harmaa", col_brown: "ruskea", col_beige: "beige", col_pink: "vaaleanpunainen", col_red: "punainen", col_orange: "oranssi", col_yellow: "keltainen", col_green: "vihreä", col_teal: "sinivihreä", col_blue: "sininen", col_violet: "violetti", mo_night: "yö", mo_dawn: "aamun ensi valo", mo_dusk: "sininen hetki", mo_evening: "ilta", mo_clear: "kirkas taivas", mo_overcast: "harmaa taivas", mo_fog: "sumu", mo_rain: "sade", mo_snow: "lumi", mo_storm: "ukkonen", mo_spring: "kevät", mo_summer: "kesä", mo_autumn: "syksy", mo_winter: "talvi", memory1: "vuosi sitten tänään säilytit teoksen {p}", memory1_song: "vuosi sitten tänään säilytit teoksen {p}, kun soi {s}", memory: "{n} vuotta sitten tänään säilytit teoksen {p}", memory_song: "{n} vuotta sitten tänään säilytit teoksen {p}, kun soi {s}", year_ready: "vuotesi {y} seinällä on valmis · näppäin Y", tip_year: "Vuotesi korttina: säilytetyt maalaukset kuukausi kuukaudelta, Työpöydälle", yr_title: "vuotesi seinällä", yr_hours: "tuntia seinällä", yr_most_kept: "eniten säilytetty", yr_museum: "museosi", yr_song: "musiikki sydänten takana", yr_painter: "maalari, jonka kanssa elit", yr_quiet: "hiljaiset kuukaudet", yr_none_quiet: "maalaus säilytetty joka kuukausi", yr_card: "tee korttini {y}", yr_in_months: "maalauksia säilytetty {n}/12 kuukautena",
      tip_theme: "Seinän väri: yhdeksän sävyä, tai maalauksen oma", tip_swap: "Toinen maalaus samaan kappaleeseen", tip_keep: "Säilytä tämä maalaus. Seinä oppii siitä, mitä säilytät", tip_kept: "Säilyttämäsi maalaukset ja kappale, joka soi", tip_next: "Seuraava kappale; seinä seuraa heti", tip_prefs: "Asetukset: kieli, paikka, yksiköt, tahti, miten seinä valitsee, päivitykset",
      st_loading: "ladataan maalausta", st_museum: "museo ei vastaa, kokeillaan toista", st_choosing: "valitaan toista maalausta", st_reading: "luetaan albumin kantta", st_next: "seuraava kappale", st_player: "soitin ei vastaa",
      playing: "soi", paused: "tauolla", paused_rot: "tauolla · seinä vaihtuu",
      sunset_in: "auringonlasku {n} min kuluttua", blue_hour: "sininen hetki", set_at: "aurinko laski klo {t}", first_light_in: "ensimmäinen valo {n} min kuluttua", blue_morning: "aamun sininen hetki", rise_at: "nousi klo {t}",
      clear: "Selkeää", mostly_clear: "Enimmäkseen selkeää", partly: "Puolipilvistä", overcast: "Pilvistä", fog: "Sumua", rime: "Jäätävää sumua", drizzle_l: "Heikkoa tihkua", drizzle: "Tihkua", drizzle_d: "Sankkaa tihkua", fdrizzle: "Jäätävää tihkua", rain_l: "Heikkoa sadetta", rain: "Sadetta", rain_h: "Rankkasadetta", frain: "Jäätävää sadetta", snow_l: "Heikkoa lumisadetta", snow: "Lumisadetta", snow_h: "Runsasta lumisadetta", showers: "Sadekuuroja", showers_h: "Voimakkaita kuuroja", snow_showers: "Lumikuuroja", storm: "Ukkosta",
      language: "Kieli", place: "Paikka", search_city: "hae kaupunkia", my_position: "käytä sijaintiani", locating: "paikannetaan…", not_found: "paikkaa ei löytynyt", no_position: "sijainti ei saatavilla", units: "Yksiköt", reset: "palauta config.json", update: "uusi versio {v} saatavilla", update_install: "uusi versio {v} · asenna", upd_downloading: "ladataan {p} %", upd_installing: "asennetaan…", upd_restarting: "käynnistetään uudelleen…", upd_failed: "päivitys epäonnistui · avaa sivu", upd_ready: "uusi versio {v} valmis · käynnistä uudelleen", dismiss: "ei nyt", updates: "Päivitykset", upd_click: "kysy minulta", upd_auto: "asenna suljettaessa", ver_current: "versio {v} · ajan tasalla", ver_newer: "versio {v} · {n} saatavilla", demo_kicker: "verkkodemo · ei musiikkia tässä", demo_title: "Oikea seinä kuuntelee musiikkiasi.", demo_sub: "Ilmainen sovellus sovittaa jokaisen maalauksen soivaan albumiin. Ei tiliä, päivittyy itse.", demo_how: "asennusohje", choice: "Valinta", taste_on: "oma makuni", taste_off: "yllätä minut", taste_note: "oma makuni: säilytetyt maalaukset vetävät kohti taiteilijoitaan, museoitaan ja vuosisatojaan", made_by: "tekijä", source: "lähdekoodi", pace: "Tahti", pace_note: "kuinka kauan maalaus pysyy, kun mikään ei soi", tip_card: "Tallenna kortti tästä seinästä Työpöydälle: maalaus, kilpi, kappale, päivän maalaukset", card_making: "piirretään korttia…", card_saved: "kortti tallennettu Työpöydälle", card_failed: "korttia ei voitu tehdä", today_born: "{a}, syntyi tänä päivänä {y}", today_died: "{a}, kuoli tänä päivänä {y}", tip_export: "tallenna luettelo tiedostoksi", tip_stats: "Tilastot: aika seinällä museon, vuosisadan ja maalarin mukaan", tip_full: "Koko näyttö", tip_help: "Mitä painikkeet ja näppäimet tekevät", help_title: "heure bleue", help_sub: "Maalausseinä, joka seuraa musiikkiasi. Kaikki on yksi näppäin tai pieni painike oikeassa alakulmassa.", help_close: "sulje millä tahansa näppäimellä · ? tuo tämän takaisin",
      kept: "Pidetyt", wall: "seinä", stats: "tilastot", museum: "museo", order: "järjestys", newest: "uusimmat", oldest: "vanhimmat", artist: "taiteilija", all: "kaikki", empty_kept: "Ei vielä pidettyjä. Paina L seinällä.", open: "avaa", remove: "poista", song_tip: "soi, kun pidit tämän",
      since: "alkaen {d}", empty_stats: "Ei vielä mitään.", empty_stats_sub: "Seinä kirjoittaa rivin joka kerta, kun maalaus vaihtuu.", nothing_yet: "ei vielä mitään",
      shown: "maalausta näytetty", works: "eri teosta", on_wall: "seinällä", skipped: "ohitettu", with_music: "musiikin kanssa",
      museums: "Museot", time_on_wall: "aika seinällä", centuries: "Vuosisadat", century: "{c}00-luku", painters: "Taidemaalarit", most_on_wall: "eniten seinällä", most_shown: "Eniten näytetyt", sec_skipped: "Ohitetut", skipped_sub: "ne, jotka ohitit", music: "Musiikki", music_sub: "artistit seinän takana", songs: "Kappaleet", pairings: "Parit", pairings_sub: "artisti → useimmin yhdistetty maalari", of: "{a} / {b}", by_museum: "museon mukaan", songs_hearts: "Kappaleet sydänten takana", hours: "Tunnit", hours_sub: "milloin seinä on päällä", h: "t", min: "min",
    },
    sv: { name: "Svenska",
      mood: "matchad mot albumomslaget",
      match: "Avstämning", match_cover: "omslagets färger", match_music: "musikens stämning", match_moment: "stunden", match_note: "vad ett val lyssnar på; stäng av vad du vill, ett blir kvar", why_lead: "vald för {list}", and: "och", why_cover: "omslagets {c}", why_music: "{t} i musiken", why_hour: "{a}, som du nyss sparade", why_today: "{a}s dag", why_taste: "{a}, som du sparar", col_black: "svarta", col_white: "vita", col_grey: "grå", col_brown: "bruna", col_beige: "beige", col_pink: "rosa", col_red: "röda", col_orange: "orange", col_yellow: "gula", col_green: "gröna", col_teal: "blågröna", col_blue: "blå", col_violet: "violetta", mo_night: "natten", mo_dawn: "det första ljuset", mo_dusk: "den blå timmen", mo_evening: "kvällen", mo_clear: "den klara himlen", mo_overcast: "den grå himlen", mo_fog: "dimman", mo_rain: "regnet", mo_snow: "snön", mo_storm: "åskan", mo_spring: "våren", mo_summer: "sommaren", mo_autumn: "hösten", mo_winter: "vintern", memory1: "för ett år sedan i dag sparade du {p}", memory1_song: "för ett år sedan i dag sparade du {p} till {s}", memory: "för {n} år sedan i dag sparade du {p}", memory_song: "för {n} år sedan i dag sparade du {p} till {s}", year_ready: "ditt {y} på väggen är klart · tangent Y", tip_year: "Ditt år som kort: de sparade målningarna, månad för månad, till Skrivbordet", yr_title: "ditt år på väggen", yr_hours: "timmar på väggen", yr_most_kept: "mest sparad", yr_museum: "ditt museum", yr_song: "musiken bakom hjärtana", yr_painter: "målaren du levde med", yr_quiet: "tysta månader", yr_none_quiet: "en målning sparad varje månad", yr_card: "gör mitt kort {y}", yr_in_months: "målningar sparade {n} av 12 månader",
      tip_theme: "Väggfärg: nio toner, eller målningens egen", tip_swap: "En annan målning till samma låt", tip_keep: "Spara den här målningen. Väggen lär sig av det du sparar", tip_kept: "Dina sparade målningar, med låten som spelades", tip_next: "Nästa låt; väggen följer genast", tip_prefs: "Inställningar: språk, plats, enheter, takt, hur väggen väljer, uppdateringar",
      st_loading: "laddar målningen", st_museum: "museet svarar inte, provar ett annat", st_choosing: "väljer en annan målning", st_reading: "läser albumomslaget", st_next: "nästa låt", st_player: "spelaren svarar inte",
      playing: "spelar", paused: "pausad", paused_rot: "pausad · väggen byter",
      sunset_in: "solnedgång om {n} min", blue_hour: "blå timmen", set_at: "solen gick ner {t}", first_light_in: "första ljuset om {n} min", blue_morning: "morgonens blå timme", rise_at: "gick upp {t}",
      clear: "Klart", mostly_clear: "Mestadels klart", partly: "Halvklart", overcast: "Mulet", fog: "Dimma", rime: "Underkyld dimma", drizzle_l: "Lätt duggregn", drizzle: "Duggregn", drizzle_d: "Tätt duggregn", fdrizzle: "Underkylt duggregn", rain_l: "Lätt regn", rain: "Regn", rain_h: "Kraftigt regn", frain: "Underkylt regn", snow_l: "Lätt snöfall", snow: "Snö", snow_h: "Kraftigt snöfall", showers: "Skurar", showers_h: "Kraftiga skurar", snow_showers: "Snöbyar", storm: "Åska",
      language: "Språk", place: "Plats", search_city: "sök en stad", my_position: "använd min position", locating: "lokaliserar…", not_found: "ingen plats hittades", no_position: "position inte tillgänglig", units: "Enheter", reset: "tillbaka till config.json", update: "ny version {v} tillgänglig", update_install: "ny version {v} · installera", upd_downloading: "hämtar {p} %", upd_installing: "installerar…", upd_restarting: "startar om…", upd_failed: "uppdateringen misslyckades · öppna sidan", upd_ready: "ny version {v} klar · starta om", dismiss: "inte nu", updates: "Uppdateringar", upd_click: "fråga mig", upd_auto: "installera vid avslut", ver_current: "version {v} · aktuell", ver_newer: "version {v} · {n} tillgänglig", demo_kicker: "webbdemo · ingen musik här", demo_title: "Den riktiga väggen lyssnar på din musik.", demo_sub: "Gratisappen matchar varje målning med albumet som spelas. Inget konto, uppdaterar sig själv.", demo_how: "så installerar du", choice: "Val", taste_on: "min smak", taste_off: "överraska mig", taste_note: "min smak: sparade målningar drar mot sina konstnärer, museer och århundraden", made_by: "skapad av", source: "källkod", pace: "Takt", pace_note: "hur länge en målning stannar när inget spelas", tip_card: "Spara ett kort av väggen på Skrivbordet: målning, skylt, låt, dagens målningar", card_making: "ritar kortet…", card_saved: "kortet sparat på Skrivbordet", card_failed: "kortet kunde inte skapas", today_born: "{a}, född denna dag {y}", today_died: "{a}, död denna dag {y}", tip_export: "spara listan som fil", tip_stats: "Statistik: tid på väggen per museum, århundrade och målare", tip_full: "Helskärm", tip_help: "Vad knapparna och tangenterna gör", help_title: "heure bleue", help_sub: "En tavelvägg som följer din musik. Allt är en tangent eller en liten knapp nere till höger.", help_close: "tryck en tangent för att stänga · ? tar dig hit igen",
      kept: "Behållna", wall: "vägg", stats: "statistik", museum: "museum", order: "ordning", newest: "nyaste", oldest: "äldsta", artist: "konstnär", all: "alla", empty_kept: "Inget behållet än. Tryck L på väggen.", open: "öppna", remove: "ta bort", song_tip: "spelades när du behöll den här",
      since: "sedan {d}", empty_stats: "Inget än.", empty_stats_sub: "Väggen skriver en rad varje gång målningen byts.", nothing_yet: "inget än",
      shown: "målningar visade", works: "olika verk", on_wall: "på väggen", skipped: "överhoppade", with_music: "med musik",
      museums: "Museer", time_on_wall: "tid på väggen", centuries: "Århundraden", century: "{c}00-talet", painters: "Målare", most_on_wall: "mest på väggen", most_shown: "Mest visade", sec_skipped: "Överhoppade", skipped_sub: "de du gick vidare från", music: "Musik", music_sub: "artisterna bakom väggen", songs: "Låtar", pairings: "Par", pairings_sub: "artist → oftast matchad målare", of: "{a} av {b}", by_museum: "per museum", songs_hearts: "Låtarna bakom hjärtana", hours: "Timmar", hours_sub: "när väggen är på", h: "h", min: "min",
    },
    da: { name: "Dansk",
      mood: "matchet til albumcoveret",
      match: "Afstemning", match_cover: "coverets farver", match_music: "musikkens stemning", match_moment: "øjeblikket", match_note: "hvad et valg lytter til; sluk hvad du vil, ét bliver tændt", why_lead: "valgt for {list}", and: "og", why_cover: "coverets {c}", why_music: "{t} i musikken", why_hour: "{a}, som du lige gemte", why_today: "{a}s dag", why_taste: "{a}, som du gemmer", col_black: "sorte", col_white: "hvide", col_grey: "grå", col_brown: "brune", col_beige: "beige", col_pink: "rosa", col_red: "røde", col_orange: "orange", col_yellow: "gule", col_green: "grønne", col_teal: "blågrønne", col_blue: "blå", col_violet: "violette", mo_night: "natten", mo_dawn: "det første lys", mo_dusk: "den blå time", mo_evening: "aftenen", mo_clear: "den klare himmel", mo_overcast: "den grå himmel", mo_fog: "tågen", mo_rain: "regnen", mo_snow: "sneen", mo_storm: "tordenvejret", mo_spring: "foråret", mo_summer: "sommeren", mo_autumn: "efteråret", mo_winter: "vinteren", memory1: "for et år siden i dag gemte du {p}", memory1_song: "for et år siden i dag gemte du {p} til {s}", memory: "for {n} år siden i dag gemte du {p}", memory_song: "for {n} år siden i dag gemte du {p} til {s}", year_ready: "dit {y} på væggen er klar · tast Y", tip_year: "Dit år som kort: de gemte malerier, måned for måned, til Skrivebordet", yr_title: "dit år på væggen", yr_hours: "timer på væggen", yr_most_kept: "mest gemt", yr_museum: "dit museum", yr_song: "musikken bag hjerterne", yr_painter: "maleren du levede med", yr_quiet: "stille måneder", yr_none_quiet: "et maleri gemt hver måned", yr_card: "lav mit kort {y}", yr_in_months: "malerier gemt i {n} af 12 måneder",
      tip_theme: "Vægfarve: ni toner, eller maleriets egen", tip_swap: "Et andet maleri til samme sang", tip_keep: "Gem dette maleri. Væggen lærer af det, du gemmer", tip_kept: "Dine gemte malerier, med den sang der spillede", tip_next: "Næste sang; væggen følger straks", tip_prefs: "Indstillinger: sprog, sted, enheder, tempo, hvordan væggen vælger, opdateringer",
      st_loading: "henter maleriet", st_museum: "museet svarer ikke, prøver et andet", st_choosing: "vælger et andet maleri", st_reading: "læser albumcoveret", st_next: "næste sang", st_player: "afspilleren svarer ikke",
      playing: "spiller", paused: "på pause", paused_rot: "på pause · væggen skifter",
      sunset_in: "solnedgang om {n} min", blue_hour: "den blå time", set_at: "solen gik ned kl. {t}", first_light_in: "første lys om {n} min", blue_morning: "morgenens blå time", rise_at: "stod op kl. {t}",
      clear: "Klar himmel", mostly_clear: "Mest klart", partly: "Delvist skyet", overcast: "Overskyet", fog: "Tåge", rime: "Rimtåge", drizzle_l: "Let finregn", drizzle: "Finregn", drizzle_d: "Tæt finregn", fdrizzle: "Underafkølet finregn", rain_l: "Let regn", rain: "Regn", rain_h: "Kraftig regn", frain: "Isslag", snow_l: "Let sne", snow: "Sne", snow_h: "Kraftig sne", showers: "Byger", showers_h: "Kraftige byger", snow_showers: "Snebyger", storm: "Tordenvejr",
      language: "Sprog", place: "Sted", search_city: "søg en by", my_position: "brug min position", locating: "finder position…", not_found: "ingen sted fundet", no_position: "position ikke tilgængelig", units: "Enheder", reset: "tilbage til config.json", update: "ny version {v} tilgængelig", update_install: "ny version {v} · installer", upd_downloading: "henter {p} %", upd_installing: "installerer…", upd_restarting: "genstarter…", upd_failed: "opdatering mislykkedes · åbn siden", upd_ready: "ny version {v} klar · genstart", dismiss: "ikke nu", updates: "Opdateringer", upd_click: "spørg mig", upd_auto: "installér ved afslutning", ver_current: "version {v} · opdateret", ver_newer: "version {v} · {n} tilgængelig", demo_kicker: "webdemo · ingen musik her", demo_title: "Den rigtige væg lytter til din musik.", demo_sub: "Den gratis app matcher hvert maleri med det album, der spiller. Ingen konto, opdaterer sig selv.", demo_how: "sådan installerer du", choice: "Valg", taste_on: "min smag", taste_off: "overrask mig", taste_note: "min smag: gemte malerier trækker mod deres kunstnere, museer og århundreder", made_by: "lavet af", source: "kildekode", pace: "Tempo", pace_note: "hvor længe et maleri bliver, når intet spiller", tip_card: "Gem et kort af væggen på Skrivebordet: maleri, skilt, sang, dagens malerier", card_making: "tegner kortet…", card_saved: "kort gemt på Skrivebordet", card_failed: "kortet kunne ikke laves", today_born: "{a}, født på denne dag i {y}", today_died: "{a}, død på denne dag i {y}", tip_export: "gem listen som fil", tip_stats: "Statistik: tid på væggen efter museum, århundrede og maler", tip_full: "Fuld skærm", tip_help: "Hvad knapperne og tasterne gør", help_title: "heure bleue", help_sub: "En billedvæg, der følger din musik. Alt er én tast eller én lille knap nederst til højre.", help_close: "tryk en tast for at lukke · ? bringer dette tilbage",
      kept: "Beholdt", wall: "væg", stats: "statistik", museum: "museum", order: "rækkefølge", newest: "nyeste", oldest: "ældste", artist: "kunstner", all: "alle", empty_kept: "Intet beholdt endnu. Tryk L på væggen.", open: "åbn", remove: "fjern", song_tip: "spillede, da du beholdt dette",
      since: "siden {d}", empty_stats: "Intet endnu.", empty_stats_sub: "Væggen skriver en linje, hver gang maleriet skifter.", nothing_yet: "intet endnu",
      shown: "malerier vist", works: "forskellige værker", on_wall: "på væggen", skipped: "sprunget over", with_music: "med musik",
      museums: "Museer", time_on_wall: "tid på væggen", centuries: "Århundreder", century: "{c}00-tallet", painters: "Malere", most_on_wall: "mest på væggen", most_shown: "Mest viste", sec_skipped: "Sprunget over", skipped_sub: "dem du gik videre fra", music: "Musik", music_sub: "kunstnerne bag væggen", songs: "Sange", pairings: "Par", pairings_sub: "musiker → oftest matchet maler", of: "{a} af {b}", by_museum: "pr. museum", songs_hearts: "Sangene bag hjerterne", hours: "Timer", hours_sub: "når væggen er tændt", h: "t", min: "min",
    },
    pl: { name: "Polski",
      mood: "dopasowane do okładki albumu",
      match: "Dopasowanie", match_cover: "kolory okładki", match_music: "nastrój muzyki", match_moment: "chwila", match_note: "czego słucha wybór; wyłącz co chcesz, jedno zostaje", why_lead: "wybrany za {list}", and: "i", why_cover: "{c} okładki", why_music: "{t} w muzyce", why_hour: "{a}, którego właśnie zachowałeś", why_today: "dzień {a}", why_taste: "{a}, którego zachowujesz", col_black: "czerń", col_white: "biel", col_grey: "szarość", col_brown: "brąz", col_beige: "beż", col_pink: "róż", col_red: "czerwień", col_orange: "pomarańcz", col_yellow: "żółć", col_green: "zieleń", col_teal: "morski", col_blue: "błękit", col_violet: "fiolet", mo_night: "noc", mo_dawn: "pierwsze światło", mo_dusk: "niebieską godzinę", mo_evening: "wieczór", mo_clear: "czyste niebo", mo_overcast: "szare niebo", mo_fog: "mgłę", mo_rain: "deszcz", mo_snow: "śnieg", mo_storm: "burzę", mo_spring: "wiosnę", mo_summer: "lato", mo_autumn: "jesień", mo_winter: "zimę", memory1: "rok temu, tego dnia, zachowałeś {p}", memory1_song: "rok temu, tego dnia, zachowałeś {p} przy {s}", memory: "{n} lat temu, tego dnia, zachowałeś {p}", memory_song: "{n} lat temu, tego dnia, zachowałeś {p} przy {s}", year_ready: "twój {y} na ścianie jest gotowy · klawisz Y", tip_year: "Twój rok jako karta: zachowane obrazy, miesiąc po miesiącu, na Pulpit", yr_title: "twój rok na ścianie", yr_hours: "godzin na ścianie", yr_most_kept: "najczęściej zachowany", yr_museum: "twoje muzeum", yr_song: "muzyka za sercami", yr_painter: "malarz, z którym żyłeś", yr_quiet: "ciche miesiące", yr_none_quiet: "obraz zachowany co miesiąc", yr_card: "zrób moją kartę {y}", yr_in_months: "obrazy zachowane w {n} z 12 miesięcy",
      tip_theme: "Kolor ściany: dziewięć odcieni albo kolor obrazu", tip_swap: "Inny obraz do tej samej piosenki", tip_keep: "Zachowaj ten obraz. Ściana uczy się z tego, co zachowujesz", tip_kept: "Zachowane obrazy, z piosenką, która wtedy grała", tip_next: "Następna piosenka; ściana od razu podąża", tip_prefs: "Ustawienia: język, miejsce, jednostki, tempo, sposób wyboru, aktualizacje",
      st_loading: "ładowanie obrazu", st_museum: "muzeum nie odpowiada, próbujemy innego", st_choosing: "wybieranie innego obrazu", st_reading: "odczyt okładki albumu", st_next: "następny utwór", st_player: "odtwarzacz nie odpowiada",
      playing: "gra", paused: "pauza", paused_rot: "pauza · ściana się zmienia",
      sunset_in: "zachód słońca za {n} min", blue_hour: "niebieska godzina", set_at: "słońce zaszło o {t}", first_light_in: "pierwsze światło za {n} min", blue_morning: "poranna niebieska godzina", rise_at: "wzeszło o {t}",
      clear: "Bezchmurnie", mostly_clear: "Prawie bezchmurnie", partly: "Częściowe zachmurzenie", overcast: "Pochmurno", fog: "Mgła", rime: "Mgła marznąca", drizzle_l: "Lekka mżawka", drizzle: "Mżawka", drizzle_d: "Gęsta mżawka", fdrizzle: "Mżawka marznąca", rain_l: "Lekki deszcz", rain: "Deszcz", rain_h: "Ulewny deszcz", frain: "Deszcz marznący", snow_l: "Lekki śnieg", snow: "Śnieg", snow_h: "Intensywny śnieg", showers: "Przelotne opady", showers_h: "Silne przelotne opady", snow_showers: "Przelotny śnieg", storm: "Burza",
      language: "Język", place: "Miejsce", search_city: "szukaj miasta", my_position: "użyj mojej pozycji", locating: "ustalanie pozycji…", not_found: "nie znaleziono miejsca", no_position: "pozycja niedostępna", units: "Jednostki", reset: "wróć do config.json", update: "nowa wersja {v} dostępna", update_install: "nowa wersja {v} · zainstaluj", upd_downloading: "pobieranie {p} %", upd_installing: "instalowanie…", upd_restarting: "ponowne uruchamianie…", upd_failed: "aktualizacja nie powiodła się · otwórz stronę", upd_ready: "nowa wersja {v} gotowa · uruchom ponownie", dismiss: "nie teraz", updates: "Aktualizacje", upd_click: "zapytaj mnie", upd_auto: "zainstaluj przy zamknięciu", ver_current: "wersja {v} · aktualna", ver_newer: "wersja {v} · dostępna {n}", demo_kicker: "demo web · tu bez muzyki", demo_title: "Prawdziwa ściana słucha twojej muzyki.", demo_sub: "Darmowa aplikacja dopasowuje każdy obraz do grającego albumu. Bez konta, aktualizuje się sama.", demo_how: "jak zainstalować", choice: "Wybór", taste_on: "mój gust", taste_off: "zaskocz mnie", taste_note: "mój gust: zachowane obrazy ciągną ku swoim artystom, muzeom i wiekom", made_by: "autorka", source: "kod źródłowy", pace: "Tempo", pace_note: "jak długo obraz zostaje, gdy nic nie gra", tip_card: "Zapisz kartę tej ściany na Pulpicie: obraz, podpis, piosenka, obrazy dnia", card_making: "rysowanie karty…", card_saved: "karta zapisana na Pulpicie", card_failed: "nie udało się zrobić karty", today_born: "{a}, urodzony tego dnia w {y}", today_died: "{a}, zmarł tego dnia w {y}", tip_export: "zapisz listę jako plik", tip_stats: "Statystyki: czas na ścianie według muzeum, wieku i malarza", tip_full: "Pełny ekran", tip_help: "Co robią przyciski i klawisze", help_title: "heure bleue", help_sub: "Ściana obrazów, która podąża za twoją muzyką. Wszystko to jeden klawisz albo mały przycisk w prawym dolnym rogu.", help_close: "dowolny klawisz zamyka · ? przywraca ten ekran",
      kept: "Zachowane", wall: "ściana", stats: "statystyki", museum: "muzeum", order: "kolejność", newest: "najnowsze", oldest: "najstarsze", artist: "artysta", all: "wszystkie", empty_kept: "Nic jeszcze nie zachowano. Naciśnij L na ścianie.", open: "otwórz", remove: "usuń", song_tip: "grało, gdy to zachowano",
      since: "od {d}", empty_stats: "Jeszcze nic.", empty_stats_sub: "Ściana zapisuje wiersz przy każdej zmianie obrazu.", nothing_yet: "jeszcze nic",
      shown: "obrazów pokazanych", works: "różnych dzieł", on_wall: "na ścianie", skipped: "pominięte", with_music: "z muzyką",
      museums: "Muzea", time_on_wall: "czas na ścianie", centuries: "Wieki", century: "{n}. wiek", painters: "Malarze", most_on_wall: "najdłużej na ścianie", most_shown: "Najczęściej pokazywane", sec_skipped: "Pominięte", skipped_sub: "te, które pominięto", music: "Muzyka", music_sub: "artyści za ścianą", songs: "Utwory", pairings: "Pary", pairings_sub: "muzyk → najczęściej dopasowany malarz", of: "{a} z {b}", by_museum: "według muzeum", songs_hearts: "Utwory za serduszkami", hours: "Godziny", hours_sub: "kiedy ściana jest włączona", h: "godz", min: "min",
    },
    ru: { name: "Русский",
      mood: "подобрано к обложке альбома",
      match: "Созвучие", match_cover: "цвета обложки", match_music: "настроение музыки", match_moment: "момент", match_note: "что слушает выбор; выключайте что угодно, одно останется", why_lead: "выбрана за {list}", and: "и", why_cover: "{c} обложки", why_music: "{t} в музыке", why_hour: "{a}, которого вы только что сохранили", why_today: "день {a}", why_taste: "{a}, которого вы сохраняете", col_black: "чёрный", col_white: "белый", col_grey: "серый", col_brown: "коричневый", col_beige: "бежевый", col_pink: "розовый", col_red: "красный", col_orange: "оранжевый", col_yellow: "жёлтый", col_green: "зелёный", col_teal: "сине-зелёный", col_blue: "синий", col_violet: "фиолетовый", mo_night: "ночь", mo_dawn: "первый свет", mo_dusk: "синий час", mo_evening: "вечер", mo_clear: "ясное небо", mo_overcast: "серое небо", mo_fog: "туман", mo_rain: "дождь", mo_snow: "снег", mo_storm: "грозу", mo_spring: "весну", mo_summer: "лето", mo_autumn: "осень", mo_winter: "зиму", memory1: "год назад в этот день вы сохранили {p}", memory1_song: "год назад в этот день вы сохранили {p} под {s}", memory: "{n} лет назад в этот день вы сохранили {p}", memory_song: "{n} лет назад в этот день вы сохранили {p} под {s}", year_ready: "ваш {y} на стене готов · клавиша Y", tip_year: "Ваш год как карточка: сохранённые картины месяц за месяцем, на Рабочий стол", yr_title: "ваш год на стене", yr_hours: "часов на стене", yr_most_kept: "чаще всего сохраняли", yr_museum: "ваш музей", yr_song: "музыка за сердцами", yr_painter: "художник, с которым вы жили", yr_quiet: "тихие месяцы", yr_none_quiet: "картина сохранена каждый месяц", yr_card: "сделать мою карточку {y}", yr_in_months: "картины сохранены в {n} из 12 месяцев",
      tip_theme: "Цвет стены: девять оттенков или цвет картины", tip_swap: "Другая картина к той же песне", tip_keep: "Сохранить картину. Стена учится на том, что вы сохраняете", tip_kept: "Сохранённые картины и песня, которая тогда играла", tip_next: "Следующая песня; стена сразу следует", tip_prefs: "Настройки: язык, место, единицы, темп, способ выбора, обновления",
      st_loading: "загрузка картины", st_museum: "музей не отвечает, пробуем другой", st_choosing: "выбор другой картины", st_reading: "чтение обложки альбома", st_next: "следующая песня", st_player: "плеер не отвечает",
      playing: "играет", paused: "пауза", paused_rot: "пауза · стена меняется",
      sunset_in: "закат через {n} мин", blue_hour: "синий час", set_at: "солнце зашло в {t}", first_light_in: "первый свет через {n} мин", blue_morning: "утренний синий час", rise_at: "взошло в {t}",
      clear: "Ясно", mostly_clear: "Почти ясно", partly: "Переменная облачность", overcast: "Пасмурно", fog: "Туман", rime: "Изморозь", drizzle_l: "Лёгкая морось", drizzle: "Морось", drizzle_d: "Густая морось", fdrizzle: "Ледяная морось", rain_l: "Небольшой дождь", rain: "Дождь", rain_h: "Сильный дождь", frain: "Ледяной дождь", snow_l: "Небольшой снег", snow: "Снег", snow_h: "Сильный снег", showers: "Ливни", showers_h: "Сильные ливни", snow_showers: "Снежные заряды", storm: "Гроза",
      language: "Язык", place: "Место", search_city: "найти город", my_position: "использовать моё положение", locating: "определение…", not_found: "место не найдено", no_position: "положение недоступно", units: "Единицы", reset: "вернуть config.json", update: "доступна новая версия {v}", update_install: "новая версия {v} · установить", upd_downloading: "загрузка {p} %", upd_installing: "установка…", upd_restarting: "перезапуск…", upd_failed: "ошибка обновления · открыть страницу", upd_ready: "новая версия {v} готова · перезапустить", dismiss: "не сейчас", updates: "Обновления", upd_click: "спрашивать", upd_auto: "установить при выходе", ver_current: "версия {v} · актуальна", ver_newer: "версия {v} · доступна {n}", demo_kicker: "веб-демо · здесь без музыки", demo_title: "Настоящая стена слушает вашу музыку.", demo_sub: "Бесплатное приложение подбирает картину к играющему альбому. Без аккаунта, обновляется само.", demo_how: "как установить", choice: "Выбор", taste_on: "мой вкус", taste_off: "удиви меня", taste_note: "мой вкус: сохранённые картины тянут к своим художникам, музеям и векам", made_by: "автор", source: "исходный код", pace: "Темп", pace_note: "сколько картина остаётся, когда ничего не играет", tip_card: "Сохранить карточку стены на Рабочий стол: картина, этикетка, песня, картины дня", card_making: "рисуем карточку…", card_saved: "карточка сохранена на Рабочий стол", card_failed: "не удалось сделать карточку", today_born: "{a}, родился в этот день в {y}", today_died: "{a}, умер в этот день в {y}", tip_export: "сохранить список в файл", tip_stats: "Статистика: время на стене по музеям, векам и художникам", tip_full: "Во весь экран", tip_help: "Что делают кнопки и клавиши", help_title: "heure bleue", help_sub: "Стена картин, которая следует за вашей музыкой. Всё — одна клавиша или маленькая кнопка справа внизу.", help_close: "любая клавиша закрывает · ? возвращает сюда",
      kept: "Оставленные", wall: "стена", stats: "статистика", museum: "музей", order: "порядок", newest: "новые", oldest: "старые", artist: "художник", all: "все", empty_kept: "Пока ничего не оставлено. Нажмите L на стене.", open: "открыть", remove: "убрать", song_tip: "играло, когда вы оставили это",
      since: "с {d}", empty_stats: "Пока ничего.", empty_stats_sub: "Стена пишет строку при каждой смене картины.", nothing_yet: "пока ничего",
      shown: "картин показано", works: "разных работ", on_wall: "на стене", skipped: "пропущено", with_music: "с музыкой",
      museums: "Музеи", time_on_wall: "время на стене", centuries: "Века", century: "{n} век", painters: "Художники", most_on_wall: "дольше всех на стене", most_shown: "Чаще всего показаны", sec_skipped: "Пропущенные", skipped_sub: "те, что вы пролистнули", music: "Музыка", music_sub: "артисты за стеной", songs: "Песни", pairings: "Пары", pairings_sub: "музыкант → чаще всего подобранный художник", of: "{a} из {b}", by_museum: "по музеям", songs_hearts: "Песни за сердечками", hours: "Часы", hours_sub: "когда стена включена", h: "ч", min: "мин",
    },
    ja: { name: "日本語",
      mood: "アルバムジャケットに合わせて",
      match: "合わせ方", match_cover: "ジャケットの色", match_music: "音楽の雰囲気", match_moment: "いまこの時", match_note: "選ぶときに聴くもの。どれでも切れますが、ひとつは残ります", why_lead: "{list}で選びました", and: "と", why_cover: "ジャケットの{c}", why_music: "音楽の{t}", why_hour: "いま保存した{a}", why_today: "{a}の日", why_taste: "あなたが保存している{a}", col_black: "黒", col_white: "白", col_grey: "灰色", col_brown: "茶色", col_beige: "ベージュ", col_pink: "桃色", col_red: "赤", col_orange: "橙色", col_yellow: "黄色", col_green: "緑", col_teal: "青緑", col_blue: "青", col_violet: "紫", mo_night: "夜", mo_dawn: "朝の最初の光", mo_dusk: "ブルーアワー", mo_evening: "夕方", mo_clear: "晴れた空", mo_overcast: "灰色の空", mo_fog: "霧", mo_rain: "雨", mo_snow: "雪", mo_storm: "嵐", mo_spring: "春", mo_summer: "夏", mo_autumn: "秋", mo_winter: "冬", memory1: "一年前の今日、{p}を保存しました", memory1_song: "一年前の今日、{s}を聴きながら{p}を保存しました", memory: "{n}年前の今日、{p}を保存しました", memory_song: "{n}年前の今日、{s}を聴きながら{p}を保存しました", year_ready: "壁の{y}年ができました · Yキー", tip_year: "一年をカードに: 保存した絵を月ごとに、デスクトップへ", yr_title: "壁のあなたの一年", yr_hours: "壁にいた時間", yr_most_kept: "いちばん保存した", yr_museum: "あなたの美術館", yr_song: "ハートの裏の音楽", yr_painter: "いっしょに過ごした画家", yr_quiet: "静かな月", yr_none_quiet: "毎月ひとつ絵を保存", yr_card: "{y}年のカードを作る", yr_in_months: "12か月のうち{n}か月で絵を保存",
      tip_theme: "壁の色：九つの色、または絵の色", tip_swap: "同じ曲に別の絵", tip_keep: "この絵を保存。壁は保存した絵から学びます", tip_kept: "保存した絵と、そのとき流れていた曲", tip_next: "次の曲へ。壁もすぐに変わります", tip_prefs: "設定：言語、場所、単位、間隔、選び方、アップデート",
      st_loading: "絵を読み込み中", st_museum: "美術館が応答しません。別の絵を試します", st_choosing: "別の絵を選んでいます", st_reading: "ジャケットを読み取り中", st_next: "次の曲", st_player: "プレーヤーが応答しません",
      playing: "再生中", paused: "一時停止", paused_rot: "一時停止 · 壁は回ります",
      sunset_in: "日没まで{n}分", blue_hour: "ブルーアワー", set_at: "{t}に日没", first_light_in: "日の出まで{n}分", blue_morning: "朝のブルーアワー", rise_at: "{t}に日の出",
      clear: "快晴", mostly_clear: "晴れ", partly: "薄曇り", overcast: "曇り", fog: "霧", rime: "着氷性の霧", drizzle_l: "弱い霧雨", drizzle: "霧雨", drizzle_d: "強い霧雨", fdrizzle: "着氷性の霧雨", rain_l: "小雨", rain: "雨", rain_h: "大雨", frain: "着氷性の雨", snow_l: "小雪", snow: "雪", snow_h: "大雪", showers: "にわか雨", showers_h: "強いにわか雨", snow_showers: "にわか雪", storm: "雷雨",
      language: "言語", place: "場所", search_city: "都市を検索", my_position: "現在地を使う", locating: "位置を取得中…", not_found: "場所が見つかりません", no_position: "位置を取得できません", units: "単位", reset: "config.json に戻す", update: "新しいバージョン {v} があります", update_install: "新しいバージョン {v} · インストール", upd_downloading: "ダウンロード中 {p} %", upd_installing: "インストール中…", upd_restarting: "再起動中…", upd_failed: "更新に失敗 · ページを開く", upd_ready: "新しいバージョン {v} 準備完了 · 再起動", dismiss: "あとで", updates: "アップデート", upd_click: "確認する", upd_auto: "終了時にインストール", ver_current: "バージョン {v} · 最新", ver_newer: "バージョン {v} · {n} あり", demo_kicker: "ウェブデモ · ここでは音楽なし", demo_title: "本物の壁はあなたの音楽を聴きます。", demo_sub: "無料アプリが再生中のアルバムに絵を合わせます。アカウント不要、自動更新。", demo_how: "インストール方法", choice: "選び方", taste_on: "好みに合わせて", taste_off: "おまかせ", taste_note: "好み：保存した絵の作家・美術館・時代に寄せます", made_by: "制作", source: "ソースコード", pace: "間隔", pace_note: "音楽がないとき絵が留まる時間", tip_card: "この壁のカードをデスクトップに保存：絵、ラベル、曲、今日の絵", card_making: "カードを描いています…", card_saved: "カードをデスクトップに保存しました", card_failed: "カードを作成できませんでした", today_born: "{a}、{y}年の今日に生まれる", today_died: "{a}、{y}年の今日に没す", tip_export: "一覧をファイルに保存", tip_stats: "統計：美術館・時代・画家ごとの表示時間", tip_full: "全画面", tip_help: "ボタンとキーの説明", help_title: "heure bleue", help_sub: "音楽に合わせて絵が変わる壁。すべては右下の小さなボタンかキー一つです。", help_close: "どのキーでも閉じる · ? で再表示",
      kept: "残した絵", wall: "壁", stats: "統計", museum: "美術館", order: "並び順", newest: "新しい順", oldest: "古い順", artist: "作者", all: "すべて", empty_kept: "まだ何も残していません。壁で L を押してください。", open: "開く", remove: "削除", song_tip: "残したときに流れていた曲",
      since: "{d}から", empty_stats: "まだありません。", empty_stats_sub: "絵が変わるごとに壁が1行書きます。", nothing_yet: "まだありません",
      shown: "表示した絵", works: "異なる作品", on_wall: "壁にいた時間", skipped: "スキップ", with_music: "音楽あり",
      museums: "美術館", time_on_wall: "壁にいた時間", centuries: "世紀", century: "{n}世紀", painters: "画家", most_on_wall: "最も長く壁に", most_shown: "最も多く表示", sec_skipped: "スキップした絵", skipped_sub: "飛ばした絵", music: "音楽", music_sub: "壁の裏のアーティスト", songs: "曲", pairings: "組み合わせ", pairings_sub: "アーティスト → 最も多く合わせた画家", of: "{b}中{a}", by_museum: "美術館別", songs_hearts: "ハートの裏の曲", hours: "時間帯", hours_sub: "壁がついている時間", h: "時間", min: "分",
    },
  };

  // Open-Meteo WMO weather code -> label key
  const WMO = { 0: "clear", 1: "mostly_clear", 2: "partly", 3: "overcast", 45: "fog", 48: "rime", 51: "drizzle_l", 53: "drizzle", 55: "drizzle_d", 56: "fdrizzle", 57: "fdrizzle",
    61: "rain_l", 63: "rain", 65: "rain_h", 66: "frain", 67: "frain", 71: "snow_l", 73: "snow", 75: "snow_h", 77: "snow_l", 80: "showers", 81: "showers", 82: "showers_h", 85: "snow_showers", 86: "snow_showers", 95: "storm", 96: "storm", 99: "storm" };

  const params = new URLSearchParams(location.search);
  const LS = { lang: "wall.lang", city: "wall.city", units: "wall.units" };
  let CFG = { locale: "", language: "", city: { name: "Paris", lat: 48.8566, lon: 2.3522, timezone: "Europe/Paris" }, units: "celsius" };
  let lang = "en";

  const norm = (code) => { const c = String(code || "").toLowerCase().slice(0, 2); return LANGS[c] ? c : null; };
  function pickLang() {
    const fromUrl = norm(params.get("lang"));
    if (fromUrl) { localStorage.setItem(LS.lang, fromUrl); return fromUrl; }
    return norm(localStorage.getItem(LS.lang)) || norm(CFG.language) || norm(CFG.locale) || norm(navigator.language) || "en";
  }
  function t(key, vars) {
    let s = (LANGS[lang] && LANGS[lang][key]) ?? LANGS.en[key] ?? key;
    if (vars) for (const k in vars) s = s.replaceAll(`{${k}}`, vars[k]);
    return s;
  }
  // static text: <el data-i18n="key">, titles: <el data-i18n-title="key">, placeholders: <el data-i18n-ph="key">
  function apply(root = document) {
    document.documentElement.lang = lang;
    root.querySelectorAll("[data-i18n]").forEach(el => { el.textContent = t(el.dataset.i18n); });
    root.querySelectorAll("[data-i18n-title]").forEach(el => { el.title = t(el.dataset.i18nTitle); });
    root.querySelectorAll("[data-i18n-ph]").forEach(el => { el.placeholder = t(el.dataset.i18nPh); });
    const ti = document.querySelector("title[data-i18n-doc]"); if (ti) ti.textContent = t(ti.dataset.i18nDoc);
    document.dispatchEvent(new CustomEvent("hb:lang", { detail: { lang } }));
  }
  function setLang(code) { const c = norm(code); if (!c) return; lang = c; localStorage.setItem(LS.lang, c); apply(); }
  // the regional date format follows config.json when its language matches the one on screen
  const dateLocale = () => (String(CFG.locale || "").toLowerCase().startsWith(lang) ? CFG.locale : lang);
  const ordinal = (n) => { const r = n % 100; if (r >= 11 && r <= 13) return `${n}th`; return n + ({ 1: "st", 2: "nd", 3: "rd" }[n % 10] || "th"); };
  const century = (n) => lang === "en" ? `${ordinal(n)} century` : t("century", { n, c: n - 1 });
  const wmo = (code) => t(WMO[code] || "partly");

  // place and units: browser choice over config.json
  function city() { try { const c = JSON.parse(localStorage.getItem(LS.city) || "null"); if (c && c.lat != null && c.lon != null) return c; } catch (e) {} return CFG.city; }
  function setCity(c) { if (c) localStorage.setItem(LS.city, JSON.stringify({ name: c.name, lat: +c.lat, lon: +c.lon, timezone: c.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone })); else localStorage.removeItem(LS.city); document.dispatchEvent(new CustomEvent("hb:place")); }
  const units = () => localStorage.getItem(LS.units) || CFG.units || "celsius";
  function setUnits(u) { localStorage.setItem(LS.units, u === "fahrenheit" ? "fahrenheit" : "celsius"); document.dispatchEvent(new CustomEvent("hb:place")); }
  function reset() { [LS.lang, LS.city, LS.units].forEach(k => localStorage.removeItem(k)); lang = pickLang(); apply(); document.dispatchEvent(new CustomEvent("hb:place")); }
  const overridden = () => !!(localStorage.getItem(LS.lang) || localStorage.getItem(LS.city) || localStorage.getItem(LS.units));

  // Open-Meteo geocoding, no key. Names come back in the language on screen when it has them.
  async function searchCity(q) {
    const u = `https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=6&language=${lang}&format=json`;
    const j = await (await fetch(u)).json();
    return (j.results || []).map(r => ({ name: r.name, detail: [r.admin1, r.country].filter(Boolean).join(", "), lat: r.latitude, lon: r.longitude, timezone: r.timezone }));
  }
  // the browser's position; the name comes from a free reverse lookup, else the coordinates
  function locate() {
    return new Promise((resolve, reject) => {
      if (!navigator.geolocation) return reject(new Error("no geolocation"));
      navigator.geolocation.getCurrentPosition(async (pos) => {
        const lat = +pos.coords.latitude.toFixed(4), lon = +pos.coords.longitude.toFixed(4);
        let name = `${lat}, ${lon}`;
        try {
          const j = await (await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${lat}&longitude=${lon}&localityLanguage=${lang}`)).json();
          name = j.city || j.locality || j.principalSubdivision || name;
        } catch (e) {}
        resolve({ name, lat, lon, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone });
      }, reject, { timeout: 10000, maximumAge: 600000 });
    });
  }

  // init: merge /api/config (the real server or the demo shim), then pick the language and translate the page
  let ready;
  function init(cfg) {
    if (ready) return ready;
    ready = (async () => {
      if (cfg) CFG = { ...CFG, ...cfg };
      else { try { CFG = { ...CFG, ...(await (await fetch("/api/config", { cache: "no-store" })).json()) }; } catch (e) {} }
      lang = pickLang(); apply();
      return CFG;
    })();
    return ready;
  }
  lang = pickLang(); // a first pass before the config arrives, so the page never flashes the wrong language

  // the words on the year card (drawn by the server, which has no language of its own)
  function yearLabels() {
    const fmt = new Intl.DateTimeFormat(lang, { month: "short" });
    return { title: t("yr_title"), shown: t("shown"), hours: t("yr_hours"), kept: t("kept"), most_kept: t("yr_most_kept"), museum: t("yr_museum"),
      song: t("yr_song"), painter: t("yr_painter"), quiet: t("yr_quiet"), none_quiet: t("yr_none_quiet"), in_months: t("yr_in_months"),
      months: Array.from({ length: 12 }, (_, i) => fmt.format(new Date(2024, i, 15)).replace(".", "")) };
  }

  window.HB = { LANGS, t, apply, init, setLang, yearLabels, get lang() { return lang; }, dateLocale, century, wmo, city, setCity, units, setUnits, reset, overridden, searchCity, locate, get cfg() { return CFG; } };
})();
